# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        secret:
        base64-secret: MmZkMDAwY2FmMzYyNjAxYzE4ZGFmZDRjOWQ4ZTU0YzBlN2YyNWZmZjI0NjJmN2IxN2Y0OGU2YjE5NmQ2ZmQ3MTFiZWY1MTM2ODhlZTIyYzBhMWIxOTRjZjVhMGRjZGZjNDk0NDYxNjVmODViOTNhZTY4YjAxNDQ1MDE4MTZkMmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/

